quarkusio/registry.quarkus.io

- .gitignore
- README.md
- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/LetsEncryptResource.java
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/admin/AdminResource.java
- src/main/java/io/quarkus/registry/app/maven/MavenResource.java
- src/main/resources/application.properties
- Moved the Qute related endpoints to its own class
- Hide Qute related endpoints from the OpenAPI Schema
- Added some OpenAPI annotations
- Expose swagger-ui in PROD
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
> Small OpenAPI related updates

- README.md
- pom.xml
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/admin/AdminResource.java
- src/main/java/io/quarkus/registry/app/security/SecurityOverrideFilter.java
- src/main/resources/application.properties
Change the TOKEN check to create security principle, that allow us to use `@RolesAllowed`.
Also changed the properties to add a default token (test) for dev and test mode
> Very basic Token security

- pom.xml
- src/main/java/io/quarkus/registry/app/CacheNames.java
- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/admin/AdminService.java
- src/main/java/io/quarkus/registry/app/health/CacheHealthCheck.java
- src/main/java/io/quarkus/registry/app/maven/MavenResource.java
- src/main/java/io/quarkus/registry/app/maven/MetadataContentProvider.java
- src/main/java/io/quarkus/registry/app/maven/cache/MavenCache.java
- src/main/java/io/quarkus/registry/app/maven/cache/MavenCacheClear.java
- src/main/java/io/quarkus/registry/app/maven/cache/MavenCacheClearInterceptor.java
- src/main/java/io/quarkus/registry/app/maven/cache/MavenCacheFilter.java
- src/main/java/io/quarkus/registry/app/maven/cache/MavenResponse.java
- src/main/resources/application.properties
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
> Moved the cache to right on the `/maven` boundary

- src/main/resources/application.properties
- src/main/resources/reflection-config.json
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
> Make sure it works in native

- pom.xml
- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/maven/PlatformsContentProvider.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/test/java/io/quarkus/registry/app/services/MavenResourceTest.java
> Narrow matching platform versions to the requested Quarkus Core version

- pom.xml
- src/main/java/io/quarkus/registry/app/CacheNames.java
- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/maven/MavenConfig.java
- src/main/java/io/quarkus/registry/app/maven/RegistryDescriptorContentProvider.java
- src/test/java/io/quarkus/registry/app/maven/ArtifactParserTest.java
- src/test/java/io/quarkus/registry/app/services/MavenResourceTest.java
- src/test/java/io/quarkus/registry/app/services/MetadataTest.java
Fixes https://github.com/quarkusio/registry.quarkus.io/issues/23
> Descriptor is now configurable

- .github/workflows/build.yml
Just like https://github.com/quarkusio/quarkus/pull/19414
> Switch to Eclipse Temurin JDK via actions/setup-java

- pom.xml
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/admin/AdminService.java
- src/main/java/io/quarkus/registry/app/events/ExtensionCatalogImportEvent.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/main/java/io/quarkus/registry/app/model/model.puml
- src/main/resources/db/migration/V1__Create_schema.sql
- src/main/resources/db/migration/V4__Introduce_pinned_platforms.sql
> Support pinned platform releases

- src/main/java/io/quarkus/registry/app/model/ExtensionRelease.java
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
This changes the SQL to check if the extension is compatible for a given Quarkus core version using the `extension_release_compatibilty` data
> Check ExtensionReleaseCompatibility table when returning extensions

- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/admin/AdminService.java
- src/main/java/io/quarkus/registry/app/events/ExtensionCatalogDeleteEvent.java
- src/test/java/io/quarkus/registry/app/admin/AdminApiTest.java
This endpoint deletes a extension catalog (platform release) given its version and platformKey
> Introduce delete extension catalog

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/main/resources/db/migration/V10__Introduce_unlisted_platforms.sql
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
- Fixes #79 
It also introduces an endpoint to maintain platform releases
> Adding `unlisted` column in `PlatformRelease`

- src/main/resources/application.properties
> Use 1 year as max-age in Strict-Transport-Security

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/util/Version.java
- src/test/java/io/quarkus/registry/app/util/VersionTest.java
This PR fixes the release order importance comparator (CR is always last)
> Fix release order importance comparator

- docs/model.puml
- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/admin/AdminService.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/main/java/io/quarkus/registry/app/util/Version.java
- src/test/java/io/quarkus/registry/app/admin/AdminApiTest.java
- src/test/java/io/quarkus/registry/app/services/VersionOrderTest.java
> Display the latest two streams (+ 1 non-stable) + pinned releases

- src/main/java/db/migration/R__Fix_Sortable_Versions.java
- src/main/java/io/quarkus/registry/app/util/Version.java
- src/test/java/io/quarkus/registry/app/util/VersionTest.java
> Handle RC versions as CR

- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
The test is disabled, since at the moment we do seem to assume forward compatibility. (That is, we assume a non-platform extension written for Quarkus 2 will work for Quarkus 3.)
Sharing the test in case it's useful for TDD-ing.
> Add test that we do not assume forward compatibility. 

- src/main/java/io/quarkus/registry/app/model/ExtensionRelease.java
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
> Assume that extensions are compatible based on the major release version by default

- src/main/java/io/quarkus/registry/app/model/ExtensionRelease.java
> Use MAJOR_VERSION.0.0.A for upper and lower bounds

- pom.xml
- src/main/resources/application.properties
This reverts commit bf668c57ad625d68bc45dd0925cd84b6c6909866.
- Closes #140
- Closes #141
> Revert "Downgrade to Quarkus 2.12.3.Final"

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
See #148 for discussion. Resolves #148.
> Fill in metadata for platform extensions in client API

- docs/model.puml
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/main/java/io/quarkus/registry/app/model/PlatformStream.java
- src/main/resources/db/migration/V12__Introduce_pinned_platform_streams.sql
- src/test/java/io/quarkus/registry/app/PlatformStreamTest.java
- Fixes #156
```mermaid
classDiagram
class PlatformStream {
+ String streamKey
- String streamKeySortable
+ String name
+ boolean unlisted
+ boolean pinned
+ Map<String,Object> metadata
}
```
> Introduce `pinned` in `PlatformStream` entity

- src/main/java/io/quarkus/registry/app/model/ExtensionRelease.java
- src/main/resources/application.properties
Bring queries that take 2 seconds to queries that takes dozens of ms.
> Rewrite ExtensionRelease named queries with DISTINCT ON

- pom.xml
Reverts quarkusio/registry.quarkus.io#173
> Revert "Bump quarkus.version from 2.16.3.Final to 2.16.4.Final"

- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/maven/MavenResource.java
- src/main/java/io/quarkus/registry/app/metrics/MetricsConfiguration.java
- src/main/resources/application.properties
> Update metrics to reduce the number of buckets

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/model/PlatformStream.java
- src/main/resources/db/migration/V19__Introduce_Platform_Stream_lts.sql
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
- src/test/java/io/quarkus/registry/app/admin/AdminApiTest.java
> Include LTS flag in the `/client/platforms` endpoint

- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/test/java/io/quarkus/registry/app/PlatformStreamTest.java
- src/test/java/io/quarkus/registry/app/admin/AdminApiTest.java
- src/test/java/io/quarkus/registry/app/services/MavenResourceTest.java
Besides including pinned streams, this will trim down the list of recommended streams up to the latest stable version.
- Fixes #233
> Trim down the list of recommended streams

- pom.xml
Created from `quarkus update -P=3.8.3.redhat-00003`
> Bump to Quarkus 3.8.3.redhat-00003

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
This fixes the OpenAPI description for the `/platforms` endpoint
> Fix OpenAPI description

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/publish_docker.yml
- src/main/java/io/quarkus/registry/app/util/Version.java
- src/test/java/io/quarkus/registry/app/DatabaseRegistryClientTest.java
- src/test/java/io/quarkus/registry/app/util/VersionTest.java
Versions ending with `SNAPSHOT` are pre-final versions
> Consider SNAPSHOTS as pre-final too

- src/main/java/io/quarkus/registry/app/maven/MavenResource.java
- src/main/java/io/quarkus/registry/app/model/PlatformRelease.java
- src/test/java/io/quarkus/registry/app/services/MavenResourceTest.java
> Introduce welcome page in /maven

- src/test/java/io/quarkus/registry/app/util/VersionTest.java
- Add test case for validating sorting logic of 4-digit version numbers.
> Add tests for version sorting with 4-digit components

- src/main/java/db/migration/R__Fix_Sortable_Versions.java
- src/main/java/io/quarkus/registry/app/util/Version.java
- src/test/java/io/quarkus/registry/app/util/VersionTest.java
> Fix sortable version

- src/main/java/io/quarkus/registry/app/admin/AdminApi.java
- src/main/java/io/quarkus/registry/app/model/Platform.java
- src/test/java/io/quarkus/registry/app/admin/AdminApiTest.java
- **Introduce DELETE for PlatformStreams**
- **Test if metadataJson is not empty too**
- **Add tests for Delete Stream API**
> Introduce DELETE for PlatformStreams

- src/main/java/io/quarkus/registry/app/DatabaseRegistryClient.java
Removed the update policy setting from the registry configuration.
> Remove update policy from registry configuration
